In [5]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [6]:
roadrating = pd.read_csv("RoadRatings2015.csv")

In [7]:
roadrating.head()

,block,streetName,streetType,streetDirection,overall,crack,patch,length,width,dateRated,dateLastOverlay,flushOil,class,pavement,streetID
0,0,KINGSLEY,PL,NaN,5.0,2.0,4.0,606.0,0.0,4/15,NaN,NaN,Local,NaN,12572861
1,100,ABERDEEN,TER,NaN,6.0,3.0,4.0,530.0,22.0,4/14,1988,O,Local,3,12581174
2,100,ACADEMY,PL,NaN,6.0,4.0,2.0,588.0,28.0,4/15,NaN,O,Local,3,12576512
3,100,ACADEMY,ST,NaN,8.0,4.0,4.0,325.0,25.0,4/15,1996,O,Local,3,12571714
4,100,ADAMS,ST,E,10.0,5.0,5.0,176.0,64.0,6/15,2015,F,Local,6,12577644

In [8]:
stType = roadrating['streetType'].unique()
stType

array(['PL', 'TER', 'ST', 'DR', 'RD', 'AVE', 'CIR', 'LN', 'PKWY', 'BLVD',
       'CT', 'PARK', 'SQ'], dtype=object)

In [10]:
stTypeNum = (0,1,2,3,4,5,6,7,8,9,10,11,12)
st = [(stType[y],y+1) for y in stTypeNum]
st

[('PL', 1),
 ('TER', 2),
 ('ST', 3),
 ('DR', 4),
 ('RD', 5),
 ('AVE', 6),
 ('CIR', 7),
 ('LN', 8),
 ('PKWY', 9),
 ('BLVD', 10),
 ('CT', 11),
 ('PARK', 12),
 ('SQ', 13)]

In [11]:
newst = []
for i in roadrating['streetType']:
    j = [x[0] for x in st].index(i)
    newst.append((st[j][1]))
newst
roadrating.insert(3,'stretTypeNum',newst)

In [12]:
roadrating.head()

,block,streetName,streetType,stretTypeNum,streetDirection,overall,crack,patch,length,width,dateRated,dateLastOverlay,flushOil,class,pavement,streetID
0,0,KINGSLEY,PL,1,NaN,5.0,2.0,4.0,606.0,0.0,4/15,NaN,NaN,Local,NaN,12572861
1,100,ABERDEEN,TER,2,NaN,6.0,3.0,4.0,530.0,22.0,4/14,1988,O,Local,3,12581174
2,100,ACADEMY,PL,1,NaN,6.0,4.0,2.0,588.0,28.0,4/15,NaN,O,Local,3,12576512
3,100,ACADEMY,ST,3,NaN,8.0,4.0,4.0,325.0,25.0,4/15,1996,O,Local,3,12571714
4,100,ADAMS,ST,3,E,10.0,5.0,5.0,176.0,64.0,6/15,2015,F,Local,6,12577644

In [13]:
flushoil = roadrating['flushOil'].unique()
flushoilnum = [1,2,3,4,1,5,6]
foil = [(flushoil[y],flushoilnum[y]) for y in range(7)]
foil

[(nan, 1), ('O', 2), ('F', 3), ('PRI', 4), ('?', 1), ('OF', 5), ('DPW', 6)]

In [14]:
newfo = []
for i in roadrating['flushOil']:
    j = [x[0] for x in foil].index(i)
    newfo.append((foil[j][1]))
newfo
roadrating.insert(13,'flushOilNum',newfo)

In [15]:
roadrating.head()

,block,streetName,streetType,stretTypeNum,streetDirection,overall,crack,patch,length,width,dateRated,dateLastOverlay,flushOil,flushOilNum,class,pavement,streetID
0,0,KINGSLEY,PL,1,NaN,5.0,2.0,4.0,606.0,0.0,4/15,NaN,NaN,1,Local,NaN,12572861
1,100,ABERDEEN,TER,2,NaN,6.0,3.0,4.0,530.0,22.0,4/14,1988,O,2,Local,3,12581174
2,100,ACADEMY,PL,1,NaN,6.0,4.0,2.0,588.0,28.0,4/15,NaN,O,2,Local,3,12576512
3,100,ACADEMY,ST,3,NaN,8.0,4.0,4.0,325.0,25.0,4/15,1996,O,2,Local,3,12571714
4,100,ADAMS,ST,3,E,10.0,5.0,5.0,176.0,64.0,6/15,2015,F,3,Local,6,12577644

In [21]:
classD = roadrating['class'].unique()
classnum = [1,2,3,4,5]
foil = [(classD[y],classnum[y]) for y in range(5)]
foil
newclass = []
for i in roadrating['class']:
    j = [x[0] for x in foil].index(i)
    newclass.append((foil[j][1]))
newclass
roadrating.insert(13,'classnum',newclass)

ValueError: cannot insert classnum, already exists

In [20]:
roadrating

,block,streetName,streetType,stretTypeNum,streetDirection,overall,crack,patch,length,width,dateRated,dateLastOverlay,flushOil,classnum,flushOilNum,class,pavement,streetID
0,0,KINGSLEY,PL,1,NaN,5.0,2.0,4.0,606.0,0.0,4/15,NaN,NaN,1,1,Local,NaN,12572861
1,100,ABERDEEN,TER,2,NaN,6.0,3.0,4.0,530.0,22.0,4/14,1988,O,1,2,Local,3,12581174
2,100,ACADEMY,PL,1,NaN,6.0,4.0,2.0,588.0,28.0,4/15,NaN,O,1,2,Local,3,12576512
3,100,ACADEMY,ST,3,NaN,8.0,4.0,4.0,325.0,25.0,4/15,1996,O,1,2,Local,3,12571714
4,100,ADAMS,ST,3,E,10.0,5.0,5.0,176.0,64.0,6/15,2015,F,1,3,Local,6,12577644
5,100,ADAMS,ST,3,W,8.0,3.0,5.0,352.0,64.0,4/14,2000,F,1,3,Local,6,12573680
6,100,AINSLEY,DR,4,NaN,6.0,3.0,2.0,411.0,26.0,5/14,NaN,F,2,3,CO,3,12576914
7,100,AINSLEY,DR,4,NaN,6.0,3.0,2.0,411.0,26.0,5/14,NaN,F,2,3,CO,3,12576911
8,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12572940
9,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12571891
10,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12572942
11,100,ALBERT,RD,5,NaN,4.0,2.0,4.0,327.0,27.0,5/14,NaN,O,1,2,Local,3,12578942
12,100,ALDEN,ST,3,NaN,5.0,2.0,3.0,792.0,26.0,5/14,1989,O,1,2,Local,3,12576956
13,100,ALEXANDER,AVE,6,NaN,2.0,1.0,1.0,686.0,27.0,5/14,NaN,F,1,3,Local,4,12577333
14,100,ALMOND,ST,3,NaN,5.0,3.0,2.0,150.0,54.0,4/14,1993,F,1,3,Local,6,12577993
15,100,ALMOND,ST,3,NaN,5.0,3.0,2.0,150.0,54.0,4/14,1993,F,1,3,Local,6,12578006
16,100,ALTON,ST,3,NaN,6.0,3.0,3.0,1050.0,25.0,4/14,2002,O,1,2,Local,3,13002170
17,100,ALTON,ST,3,NaN,6.0,3.0,3.0,1050.0,25.0,4/14,2002,O,1,2,Local,3,13011484
18,100,ALVORD,ST,3,S,5.0,2.0,3.0,352.0,32.0,4/14,1987,F,1,3,Local,6,12580079
19,100,AMES,AVE,6,NaN,6.0,3.0,3.0,323.0,26.0,6/14,NaN,O,1,2,Local,3,12571734
20,100,AMHERST,AVE,6,NaN,7.0,4.0,3.0,557.0,25.0,5/14,2005,F,1,3,Local,4,12576881
21,100,AMIDON,DR,4,NaN,4.0,3.0,1.0,250.0,27.0,6/15,1994,F,1,3,Local,4,13002105
22,100,AMY,ST,3,NaN,8.0,4.0,4.0,792.0,27.0,4/15,1994,O,1,2,Local,3,12573417
23,100,ANDERSON,AVE,6,NaN,6.0,3.0,4.0,1150.0,25.0,5/14,1999,O,1,2,Local,3,12576600
24,100,ANDOVER,RD,5,NaN,6.0,3.0,5.0,323.0,21.0,5/14,NaN,O,1,2,Local,3,12577527
25,100,ARCH,ST,3,NaN,6.0,2.0,4.0,352.0,18.0,4/15,2002,O,1,2,Local,3,12581146
26,100,ARCHER,RD,5,NaN,7.0,3.0,5.0,323.0,28.0,3/14,2001,O,1,2,Local,3,12572325
27,100,ARDEN,DR,4,NaN,6.0,3.0,3.0,323.0,28.0,4/14,2003,O,1,2,Local,3,12571869
28,100,ARDMORE,PL,1,NaN,4.0,2.0,4.0,247.0,26.0,3/15,1985,O,1,2,Local,3,12580667
29,100,ARDMORE,PL,1,NaN,4.0,2.0,4.0,247.0,26.0,3/15,1985,O,1,2,Local,3,12580665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4834,900,SPRING,ST,3,NaN,6.0,3.0,3.0,297.0,27.0,4/14,NaN,F,1,3,Local,6,12575302
4835,900,STATE,ST,3,N,3.0,2.0,1.0,507.0,35.0,4/14,1993,F,3,3,MA,6,12575113
4836,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,NaN,F,4,3,PA,6,13002524
4837,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,NaN,F,4,3,PA,6,12577660
4838,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,NaN,F,4,3,PA,6,13002525
4839,900,STOLP,AVE,6,NaN,4.0,2.0,4.0,343.0,35.0,4/14,NaN,F,1,3,Local,6,12572920
4840,900,STOLP,AVE,6,NaN,4.0,2.0,4.0,343.0,35.0,4/14,NaN,F,1,3,Local,6,12572918
4841,900,SUNNYCREST,RD,5,NaN,6.0,3.0,3.0,276.0,24.0,4/14,NaN,O,1,2,Local,3,12580986
4842,900,TALLMAN,ST,3,NaN,6.0,3.0,4.0,327.0,30.0,4/14,2003,F,2,3,CO,6,12573269
4843,900,TEALL,AVE,6,NaN,9.0,5.0,5.0,339.0,30.0,4/14,2011,F,4,3,PA,6,12580395
4844,900,TEALL,AVE,6,NaN,9.0,5.0,5.0,339.0,30.0,4/14,2011,F,4,3,PA,6,12580389
4845,900,TOWNSEND,ST,3,N,5.0,4.0,1.0,540.0,30.0,4/14,1999,F,1,3,Local,6,12580009
4846,900,TOWNSEND,ST,3,S,8.0,4.0,2.0,921.0,34.0,4/14,2004,F,1,3,Local,6,12577666
4847,900,TURTLE,ST,3,NaN,4.0,3.0,3.0,705.0,27.0,4/14,NaN,O,1,2,Local,3,12575513
4848,900,TURTLE,ST,3,NaN,4.0,3.0,3.0,705.0,27.0,4/14,NaN,O,1,2,Local,3,12575522
4849,900,TYSON,PL,1,NaN,5.0,3.0,4.0,372.0,24.0,4/14,NaN,O,1,2,Local,3,12581256
4850,900,VALLEY,DR,4,NaN,8.0,4.0,5.0,290.0,30.0,4/15,2008,F,3,3,MA,6,12571781
4851,900,VALLEY,DR,4,NaN,8.0,4.0,5.0,290.0,30.0,4/15,2008,F,3,3,MA,6,12571782
4852,900,VELASKO,RD,5,NaN,8.0,5.0,4.0,312.0,26.0,4/14,2009,F,3,3,MA,6,12572318
4853,900,VELASKO,RD,5,NaN,8.0,5.0,4.0,312.0,26.0,4/14,2009,F,3,3,MA,6,13002140
4854,900,VINE,ST,3,NaN,7.0,4.0,5.0,408.0,27.0,4/15,2002,F,1,3,Local,6,12580357
4855,900,WADSWORTH,ST,3,NaN,6.0,4.0,3.0,845.0,27.0,4/15,"83,99",F,2,3,CO,6,12580658
4856,900,WALNUT,AVE,6,NaN,4.0,2.0,2.0,412.0,34.0,4/14,NaN,F,2,3,CO,6,12577578
4857,900,WESTCOTT,ST,3,NaN,6.0,3.0,3.0,681.0,30.0,6/15,2007,F,2,3,CO,6,12578476
4858,900,WESTMORELAND,AVE,6,NaN,7.0,4.0,3.0,790.0,28.0,5/14,2005,F,1,3,Local,6,12578498
4859,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,13013155
4860,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,12572797
4861,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,13013154
4862,900,WILLOW,ST,3,E,3.0,2.0,2.0,600.0,35.0,4/14,1993,F,1,3,Local,6,12580074
4863,900,WOLF,ST,3,NaN,6.0,3.0,3.0,515.0,42.0,4/15,2003,F,3,3,MA,6,12575531

In [22]:
foil

[('Local', 1), ('CO', 2), ('MA', 3), ('PA', 4), ('Parks', 5)]

In [18]:
roadrating['dateLastOverlay'].unique()

array([nan, '1988', '1996', '2015', '2000', '2004', '1989', '1993', '2002',
       '1987', '2005', '1994', '1999', '2001', '2003', '1985', '1992',
       '1991', '1997', '2006', '1998', '2009', '1990', '2013', '2008',
       '1995', '2007', '2011', '1983', '1986', '2014', '2010', '1984',
       '1982', '1981', '2012', '92,99', '83,99'], dtype=object)

In [19]:
roadrating['class'].unique()

array(['Local', 'CO', 'MA', 'PA', 'Parks'], dtype=object)

In [49]:
import math
for i in range(1,len(roadrating['dateLastOverlay'])):
    if math.isnan(float(roadrating['dateLastOverlay'][i])) :
        roadrating['dateLastOverlay'][i] = 1985

In [50]:
roadrating

,block,streetName,streetType,stretTypeNum,streetDirection,overall,crack,patch,length,width,dateRated,dateLastOverlay,flushOil,classnum,flushOilNum,class,pavement,streetID
0,0,KINGSLEY,PL,1,NaN,5.0,2.0,4.0,606.0,0.0,4/15,NaN,NaN,1,1,Local,NaN,12572861
1,100,ABERDEEN,TER,2,NaN,6.0,3.0,4.0,530.0,22.0,4/14,1988,O,1,2,Local,3,12581174
2,100,ACADEMY,PL,1,NaN,6.0,4.0,2.0,588.0,28.0,4/15,1985,O,1,2,Local,3,12576512
3,100,ACADEMY,ST,3,NaN,8.0,4.0,4.0,325.0,25.0,4/15,1999,O,1,2,Local,3,12571714
4,100,ADAMS,ST,3,E,10.0,5.0,5.0,176.0,64.0,6/15,2015,F,1,3,Local,6,12577644
5,100,ADAMS,ST,3,W,8.0,3.0,5.0,352.0,64.0,4/14,2000,F,1,3,Local,6,12573680
6,100,AINSLEY,DR,4,NaN,6.0,3.0,2.0,411.0,26.0,5/14,1985,F,2,3,CO,3,12576914
7,100,AINSLEY,DR,4,NaN,6.0,3.0,2.0,411.0,26.0,5/14,1985,F,2,3,CO,3,12576911
8,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12572940
9,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12571891
10,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12572942
11,100,ALBERT,RD,5,NaN,4.0,2.0,4.0,327.0,27.0,5/14,1985,O,1,2,Local,3,12578942
12,100,ALDEN,ST,3,NaN,5.0,2.0,3.0,792.0,26.0,5/14,1989,O,1,2,Local,3,12576956
13,100,ALEXANDER,AVE,6,NaN,2.0,1.0,1.0,686.0,27.0,5/14,1985,F,1,3,Local,4,12577333
14,100,ALMOND,ST,3,NaN,5.0,3.0,2.0,150.0,54.0,4/14,1999,F,1,3,Local,6,12577993
15,100,ALMOND,ST,3,NaN,5.0,3.0,2.0,150.0,54.0,4/14,1999,F,1,3,Local,6,12578006
16,100,ALTON,ST,3,NaN,6.0,3.0,3.0,1050.0,25.0,4/14,2002,O,1,2,Local,3,13002170
17,100,ALTON,ST,3,NaN,6.0,3.0,3.0,1050.0,25.0,4/14,2002,O,1,2,Local,3,13011484
18,100,ALVORD,ST,3,S,5.0,2.0,3.0,352.0,32.0,4/14,1987,F,1,3,Local,6,12580079
19,100,AMES,AVE,6,NaN,6.0,3.0,3.0,323.0,26.0,6/14,1985,O,1,2,Local,3,12571734
20,100,AMHERST,AVE,6,NaN,7.0,4.0,3.0,557.0,25.0,5/14,2005,F,1,3,Local,4,12576881
21,100,AMIDON,DR,4,NaN,4.0,3.0,1.0,250.0,27.0,6/15,1999,F,1,3,Local,4,13002105
22,100,AMY,ST,3,NaN,8.0,4.0,4.0,792.0,27.0,4/15,1999,O,1,2,Local,3,12573417
23,100,ANDERSON,AVE,6,NaN,6.0,3.0,4.0,1150.0,25.0,5/14,1999,O,1,2,Local,3,12576600
24,100,ANDOVER,RD,5,NaN,6.0,3.0,5.0,323.0,21.0,5/14,1985,O,1,2,Local,3,12577527
25,100,ARCH,ST,3,NaN,6.0,2.0,4.0,352.0,18.0,4/15,2002,O,1,2,Local,3,12581146
26,100,ARCHER,RD,5,NaN,7.0,3.0,5.0,323.0,28.0,3/14,2001,O,1,2,Local,3,12572325
27,100,ARDEN,DR,4,NaN,6.0,3.0,3.0,323.0,28.0,4/14,2003,O,1,2,Local,3,12571869
28,100,ARDMORE,PL,1,NaN,4.0,2.0,4.0,247.0,26.0,3/15,1985,O,1,2,Local,3,12580667
29,100,ARDMORE,PL,1,NaN,4.0,2.0,4.0,247.0,26.0,3/15,1985,O,1,2,Local,3,12580665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4834,900,SPRING,ST,3,NaN,6.0,3.0,3.0,297.0,27.0,4/14,1985,F,1,3,Local,6,12575302
4835,900,STATE,ST,3,N,3.0,2.0,1.0,507.0,35.0,4/14,1999,F,3,3,MA,6,12575113
4836,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,1985,F,4,3,PA,6,13002524
4837,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,1985,F,4,3,PA,6,12577660
4838,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,1985,F,4,3,PA,6,13002525
4839,900,STOLP,AVE,6,NaN,4.0,2.0,4.0,343.0,35.0,4/14,1985,F,1,3,Local,6,12572920
4840,900,STOLP,AVE,6,NaN,4.0,2.0,4.0,343.0,35.0,4/14,1985,F,1,3,Local,6,12572918
4841,900,SUNNYCREST,RD,5,NaN,6.0,3.0,3.0,276.0,24.0,4/14,1985,O,1,2,Local,3,12580986
4842,900,TALLMAN,ST,3,NaN,6.0,3.0,4.0,327.0,30.0,4/14,2003,F,2,3,CO,6,12573269
4843,900,TEALL,AVE,6,NaN,9.0,5.0,5.0,339.0,30.0,4/14,2011,F,4,3,PA,6,12580395
4844,900,TEALL,AVE,6,NaN,9.0,5.0,5.0,339.0,30.0,4/14,2011,F,4,3,PA,6,12580389
4845,900,TOWNSEND,ST,3,N,5.0,4.0,1.0,540.0,30.0,4/14,1999,F,1,3,Local,6,12580009
4846,900,TOWNSEND,ST,3,S,8.0,4.0,2.0,921.0,34.0,4/14,2004,F,1,3,Local,6,12577666
4847,900,TURTLE,ST,3,NaN,4.0,3.0,3.0,705.0,27.0,4/14,1985,O,1,2,Local,3,12575513
4848,900,TURTLE,ST,3,NaN,4.0,3.0,3.0,705.0,27.0,4/14,1985,O,1,2,Local,3,12575522
4849,900,TYSON,PL,1,NaN,5.0,3.0,4.0,372.0,24.0,4/14,1985,O,1,2,Local,3,12581256
4850,900,VALLEY,DR,4,NaN,8.0,4.0,5.0,290.0,30.0,4/15,2008,F,3,3,MA,6,12571781
4851,900,VALLEY,DR,4,NaN,8.0,4.0,5.0,290.0,30.0,4/15,2008,F,3,3,MA,6,12571782
4852,900,VELASKO,RD,5,NaN,8.0,5.0,4.0,312.0,26.0,4/14,2009,F,3,3,MA,6,12572318
4853,900,VELASKO,RD,5,NaN,8.0,5.0,4.0,312.0,26.0,4/14,2009,F,3,3,MA,6,13002140
4854,900,VINE,ST,3,NaN,7.0,4.0,5.0,408.0,27.0,4/15,2002,F,1,3,Local,6,12580357
4855,900,WADSWORTH,ST,3,NaN,6.0,4.0,3.0,845.0,27.0,4/15,1999,F,2,3,CO,6,12580658
4856,900,WALNUT,AVE,6,NaN,4.0,2.0,2.0,412.0,34.0,4/14,1985,F,2,3,CO,6,12577578
4857,900,WESTCOTT,ST,3,NaN,6.0,3.0,3.0,681.0,30.0,6/15,2007,F,2,3,CO,6,12578476
4858,900,WESTMORELAND,AVE,6,NaN,7.0,4.0,3.0,790.0,28.0,5/14,2005,F,1,3,Local,6,12578498
4859,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,13013155
4860,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,12572797
4861,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,13013154
4862,900,WILLOW,ST,3,E,3.0,2.0,2.0,600.0,35.0,4/14,1999,F,1,3,Local,6,12580074
4863,900,WOLF,ST,3,NaN,6.0,3.0,3.0,515.0,42.0,4/15,2003,F,3,3,MA,6,12575531

In [51]:
roadrating['dateLastOverlay'][0] = 1985

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [52]:
roadrating

,block,streetName,streetType,stretTypeNum,streetDirection,overall,crack,patch,length,width,dateRated,dateLastOverlay,flushOil,classnum,flushOilNum,class,pavement,streetID
0,0,KINGSLEY,PL,1,NaN,5.0,2.0,4.0,606.0,0.0,4/15,1985,NaN,1,1,Local,NaN,12572861
1,100,ABERDEEN,TER,2,NaN,6.0,3.0,4.0,530.0,22.0,4/14,1988,O,1,2,Local,3,12581174
2,100,ACADEMY,PL,1,NaN,6.0,4.0,2.0,588.0,28.0,4/15,1985,O,1,2,Local,3,12576512
3,100,ACADEMY,ST,3,NaN,8.0,4.0,4.0,325.0,25.0,4/15,1999,O,1,2,Local,3,12571714
4,100,ADAMS,ST,3,E,10.0,5.0,5.0,176.0,64.0,6/15,2015,F,1,3,Local,6,12577644
5,100,ADAMS,ST,3,W,8.0,3.0,5.0,352.0,64.0,4/14,2000,F,1,3,Local,6,12573680
6,100,AINSLEY,DR,4,NaN,6.0,3.0,2.0,411.0,26.0,5/14,1985,F,2,3,CO,3,12576914
7,100,AINSLEY,DR,4,NaN,6.0,3.0,2.0,411.0,26.0,5/14,1985,F,2,3,CO,3,12576911
8,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12572940
9,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12571891
10,100,ALANSON,RD,5,NaN,5.0,2.0,5.0,880.0,18.0,3/15,2004,F,1,3,Local,6,12572942
11,100,ALBERT,RD,5,NaN,4.0,2.0,4.0,327.0,27.0,5/14,1985,O,1,2,Local,3,12578942
12,100,ALDEN,ST,3,NaN,5.0,2.0,3.0,792.0,26.0,5/14,1989,O,1,2,Local,3,12576956
13,100,ALEXANDER,AVE,6,NaN,2.0,1.0,1.0,686.0,27.0,5/14,1985,F,1,3,Local,4,12577333
14,100,ALMOND,ST,3,NaN,5.0,3.0,2.0,150.0,54.0,4/14,1999,F,1,3,Local,6,12577993
15,100,ALMOND,ST,3,NaN,5.0,3.0,2.0,150.0,54.0,4/14,1999,F,1,3,Local,6,12578006
16,100,ALTON,ST,3,NaN,6.0,3.0,3.0,1050.0,25.0,4/14,2002,O,1,2,Local,3,13002170
17,100,ALTON,ST,3,NaN,6.0,3.0,3.0,1050.0,25.0,4/14,2002,O,1,2,Local,3,13011484
18,100,ALVORD,ST,3,S,5.0,2.0,3.0,352.0,32.0,4/14,1987,F,1,3,Local,6,12580079
19,100,AMES,AVE,6,NaN,6.0,3.0,3.0,323.0,26.0,6/14,1985,O,1,2,Local,3,12571734
20,100,AMHERST,AVE,6,NaN,7.0,4.0,3.0,557.0,25.0,5/14,2005,F,1,3,Local,4,12576881
21,100,AMIDON,DR,4,NaN,4.0,3.0,1.0,250.0,27.0,6/15,1999,F,1,3,Local,4,13002105
22,100,AMY,ST,3,NaN,8.0,4.0,4.0,792.0,27.0,4/15,1999,O,1,2,Local,3,12573417
23,100,ANDERSON,AVE,6,NaN,6.0,3.0,4.0,1150.0,25.0,5/14,1999,O,1,2,Local,3,12576600
24,100,ANDOVER,RD,5,NaN,6.0,3.0,5.0,323.0,21.0,5/14,1985,O,1,2,Local,3,12577527
25,100,ARCH,ST,3,NaN,6.0,2.0,4.0,352.0,18.0,4/15,2002,O,1,2,Local,3,12581146
26,100,ARCHER,RD,5,NaN,7.0,3.0,5.0,323.0,28.0,3/14,2001,O,1,2,Local,3,12572325
27,100,ARDEN,DR,4,NaN,6.0,3.0,3.0,323.0,28.0,4/14,2003,O,1,2,Local,3,12571869
28,100,ARDMORE,PL,1,NaN,4.0,2.0,4.0,247.0,26.0,3/15,1985,O,1,2,Local,3,12580667
29,100,ARDMORE,PL,1,NaN,4.0,2.0,4.0,247.0,26.0,3/15,1985,O,1,2,Local,3,12580665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4834,900,SPRING,ST,3,NaN,6.0,3.0,3.0,297.0,27.0,4/14,1985,F,1,3,Local,6,12575302
4835,900,STATE,ST,3,N,3.0,2.0,1.0,507.0,35.0,4/14,1999,F,3,3,MA,6,12575113
4836,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,1985,F,4,3,PA,6,13002524
4837,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,1985,F,4,3,PA,6,12577660
4838,900,STATE,ST,3,S,5.0,3.0,1.0,1056.0,45.0,4/15,1985,F,4,3,PA,6,13002525
4839,900,STOLP,AVE,6,NaN,4.0,2.0,4.0,343.0,35.0,4/14,1985,F,1,3,Local,6,12572920
4840,900,STOLP,AVE,6,NaN,4.0,2.0,4.0,343.0,35.0,4/14,1985,F,1,3,Local,6,12572918
4841,900,SUNNYCREST,RD,5,NaN,6.0,3.0,3.0,276.0,24.0,4/14,1985,O,1,2,Local,3,12580986
4842,900,TALLMAN,ST,3,NaN,6.0,3.0,4.0,327.0,30.0,4/14,2003,F,2,3,CO,6,12573269
4843,900,TEALL,AVE,6,NaN,9.0,5.0,5.0,339.0,30.0,4/14,2011,F,4,3,PA,6,12580395
4844,900,TEALL,AVE,6,NaN,9.0,5.0,5.0,339.0,30.0,4/14,2011,F,4,3,PA,6,12580389
4845,900,TOWNSEND,ST,3,N,5.0,4.0,1.0,540.0,30.0,4/14,1999,F,1,3,Local,6,12580009
4846,900,TOWNSEND,ST,3,S,8.0,4.0,2.0,921.0,34.0,4/14,2004,F,1,3,Local,6,12577666
4847,900,TURTLE,ST,3,NaN,4.0,3.0,3.0,705.0,27.0,4/14,1985,O,1,2,Local,3,12575513
4848,900,TURTLE,ST,3,NaN,4.0,3.0,3.0,705.0,27.0,4/14,1985,O,1,2,Local,3,12575522
4849,900,TYSON,PL,1,NaN,5.0,3.0,4.0,372.0,24.0,4/14,1985,O,1,2,Local,3,12581256
4850,900,VALLEY,DR,4,NaN,8.0,4.0,5.0,290.0,30.0,4/15,2008,F,3,3,MA,6,12571781
4851,900,VALLEY,DR,4,NaN,8.0,4.0,5.0,290.0,30.0,4/15,2008,F,3,3,MA,6,12571782
4852,900,VELASKO,RD,5,NaN,8.0,5.0,4.0,312.0,26.0,4/14,2009,F,3,3,MA,6,12572318
4853,900,VELASKO,RD,5,NaN,8.0,5.0,4.0,312.0,26.0,4/14,2009,F,3,3,MA,6,13002140
4854,900,VINE,ST,3,NaN,7.0,4.0,5.0,408.0,27.0,4/15,2002,F,1,3,Local,6,12580357
4855,900,WADSWORTH,ST,3,NaN,6.0,4.0,3.0,845.0,27.0,4/15,1999,F,2,3,CO,6,12580658
4856,900,WALNUT,AVE,6,NaN,4.0,2.0,2.0,412.0,34.0,4/14,1985,F,2,3,CO,6,12577578
4857,900,WESTCOTT,ST,3,NaN,6.0,3.0,3.0,681.0,30.0,6/15,2007,F,2,3,CO,6,12578476
4858,900,WESTMORELAND,AVE,6,NaN,7.0,4.0,3.0,790.0,28.0,5/14,2005,F,1,3,Local,6,12578498
4859,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,13013155
4860,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,12572797
4861,900,WILLIS,AVE,6,NaN,7.0,4.0,4.0,590.0,36.0,4/15,2004,F,1,3,Local,6,13013154
4862,900,WILLOW,ST,3,E,3.0,2.0,2.0,600.0,35.0,4/14,1999,F,1,3,Local,6,12580074
4863,900,WOLF,ST,3,NaN,6.0,3.0,3.0,515.0,42.0,4/15,2003,F,3,3,MA,6,12575531

In [53]:
roadrating['dateLastOverlay'].unique()

array([1985, '1988', 1999, '2015', '2000', '2004', '1989', '2002', '1987',
       '2005', '2001', '2003', '1985', '2006', '2009', '2013', '2008',
       '2007', '2011', '1983', '1986', '2014', '2010', '1984', '1982',
       '1981', '2012'], dtype=object)

In [ ]:
roadrating.columns
for i in range(0,len(roadrating['dateLastOverlay'])):
    roadrating['overlaydiff'][i] = 2015 - roadrating['dateLastOverlay'][i]